export const ADD_WINGO_BATLE_REQUEST = "ADD_WINGO_BATLE_REQUEST";
export const ADD_WINGO_BATLE_SUCCESS = "ADD_WINGO_BATLE_SUCCESS";
export const ADD_WINGO_BATLET_FAIL = "ADD_WINGO_BATLE_FAIL";  

export const GAME_HISTORY_REQUEST = "GAME_HISTORY_REQUEST";
export const GAME_HISTORY_SUCCESS = "GAME_HISTORY_SUCCESS";
export const GAME_HISTORY_FAIL = "GAME_HISTORY_FAIL";  

export const GAME_RESULT_HISTORY_REQUEST = "GAME_RESULT_HISTORY_REQUEST";
export const GAME_RESULT_HISTORY_SUCCESS = "GAME_RESULT_HISTORY_SUCCESS";
export const GAME_RESULT_HISTORY_FAIL = "GAM_RESULTE_HISTORY_FAIL";  


export const CLEAR_ERRORS = "CLEAR_ERRORS"