export const DEPOSIT_ADD_REQ_REQUEST = "DEPOSIT_ADD_REQ_REQUEST";
export const DEPOSIT_ADD_REQ_SUCCESS = "DEPOSIT_ADD_REQ_SUCCESS";
export const DEPOSIT_ADD_REQ_FAIL = "DEPOSIT_ADD_REQ_FAIL"; 

export const DEPOSIT_HISTORY_REQUEST = "DEPOSIT_HISTORY_REQUEST";
export const DEPOSIT_HISTORY_SUCCESS = "DEPOSIT_HISTORY_SUCCESS";
export const DEPOSIT_HISTORY_FAIL = "DEPOSIT_HISTORY_FAIL";  
 
export const WITHDRAW_HISTORY_REQUEST = "WITHDRAW_HISTORY_REQUEST";
export const WITHDRAW_HISTORY_SUCCESS = "WITHDRAW_HISTORY_SUCCESS";
export const WITHDRAW_HISTORY_FAIL = "WITHDRAW_HISTORY_FAIL";  
 
export const TRANSACTION_HISTORY_REQUEST = "TRANSACTION_HISTORY_REQUEST";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_SUCCESS";
export const TRANSACTION_HISTORY_FAIL = "TRANSACTION_HISTORY_FAIL";  
 
export const ADD_MONEYWALLET_REQUEST = "ADD_MONEYWALLET_REQUEST";
export const ADD_MONEYWALLET_SUCCESS = "ADD_MONEYWALLET_SUCCESS";
export const ADD_MONEYWALLET_FAIL = "ADD_MONEYWALLET_FAIL";  
 
 
export const ADD_BANKDETAILS_REQUEST = "ADD_BANKDETAILS_REQUEST";
export const ADD_BANKDETAILS_SUCCESS = "ADD_BANKDETAILS_SUCCESS";
export const ADD_BANKDETAILST_FAIL = "ADD_BANKDETAILS_FAIL";  

export const ADD_WITHDRAW_REQ_REQUEST = "ADD_WITHDRAW_REQ_REQUEST";
export const ADD_WITHDRAW_REQ_SUCCESS = "ADD_WITHDRAW_REQ_SUCCESS";
export const ADD_WITHDRAW_REQ_FAIL = "ADD_WITHDRAW_REQ_FAIL";  


export const WALLET_BALANCE_REQUEST = "WALLET_BALANCE_REQUEST";
export const WALLET_BALANCE_SUCCESS = "WALLET_BALANCE_SUCCESS";
export const WALLET_BALANCE_FAIL = "WALLET_BALANCE_FAIL";  
 
export const GET_BANKDETAILS_REQUEST = "GET_BANKDETAILS_REQUEST";
export const GET_BANKDETAILS_SUCCESS = "GET_BANKDETAILS_SUCCESS";
export const GET_BANKDETAILST_FAIL = "GET_BANKDETAILS_FAIL";  
 
 


export const CLEAR_ERRORS = "CLEAR_ERRORS"