export const DEPOSIT_ADD_REQ_REQUEST = "DEPOSIT_ADD_REQ_REQUEST";
export const DEPOSIT_ADD_REQ_SUCCESS = "DEPOSIT_ADD_REQ_SUCCESS";
export const DEPOSIT_ADD_REQ_FAIL = "DEPOSIT_ADD_REQ_FAIL"; 

export const DEPOSIT_HISTORY_REQUEST = "DEPOSIT_HISTORY_REQUEST";
export const DEPOSIT_HISTORY_SUCCESS = "DEPOSIT_HISTORY_SUCCESS";
export const DEPOSIT_HISTORY_FAIL = "DEPOSIT_HISTORY_FAIL";  
 
export const WITHDRAW_HISTORY_REQUEST = "WITHDRAW_HISTORY_REQUEST";
export const WITHDRAW_HISTORY_SUCCESS = "WITHDRAW_HISTORY_SUCCESS";
export const WITHDRAW_HISTORY_FAIL = "WITHDRAW_HISTORY_FAIL";  
 
export const TRANSACTION_HISTORY_REQUEST = "TRANSACTION_HISTORY_REQUEST";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_SUCCESS";
export const TRANSACTION_HISTORY_FAIL = "TRANSACTION_HISTORY_FAIL";  
 
export const ADD_MONEYWALLET_REQUEST = "ADD_MONEYWALLET_REQUEST";
export const ADD_MONEYWALLET_SUCCESS = "ADD_MONEYWALLET_SUCCESS";
export const ADD_MONEYWALLET_FAIL = "ADD_MONEYWALLET_FAIL";  
 
export const CHECK_NEW_USER_REQ = "CHECK_NEW_USER_REQ";
export const CHECK_NEW_USER_SUCCESS = "CHECK_NEW_USER_RSUCCESS";
export const CHECK_NEW_USER_FAIL = "CHECK_NEW_USER_FAIL";  
 
 
export const ADD_BANKDETAILS_REQUEST = "ADD_BANKDETAILS_REQUEST";
export const ADD_BANKDETAILS_SUCCESS = "ADD_BANKDETAILS_SUCCESS";
export const ADD_BANKDETAILST_FAIL = "ADD_BANKDETAILS_FAIL";  

export const ADD_WITHDRAW_REQ_REQUEST = "ADD_WITHDRAW_REQ_REQUEST";
export const ADD_WITHDRAW_REQ_SUCCESS = "ADD_WITHDRAW_REQ_SUCCESS";
export const ADD_WITHDRAW_REQ_FAIL = "ADD_WITHDRAW_REQ_FAIL";  

export const ALL_USERS_WITHDRAW_REQ_REQUEST = "ALL_USERS_WITHDRAW_REQ_REQUEST";
export const ALL_USERS_WITHDRAW_REQ_SUCCESS = "ALL_USERS_WITHDRAW_REQ_SUCCESS";
export const ALL_USERS_WITHDRAW_REQ_FAIL = "ALL_USERS_WITHDRAW_REQ_FAIL";  

export const UPDATE_WITHDRAW_REQ_FOR_ADMIN_REQUEST = "UPDATE_WITHDRAW_REQ_FOR_ADMIN_REQUEST";
export const UPDATE_WITHDRAW_REQ_FOR_ADMIN_SUCCESS = "UPDATE_WITHDRAW_REQ_FOR_ADMIN_SUCCESS";
export const UPDATE_WITHDRAW_REQ_FOR_ADMIN_FAIL = "UPDATE_WITHDRAW_REQ_FOR_ADMIN_FAIL";

export const CLAIMED_REFER_REWARD_REQUEST = "CLAIMED_REFER_REWARD_REQUEST";
export const CLAIMED_REFER_REWARD_SUCCESS = "CLAIMED_REFER_REWARD_SUCCESS";
export const CLAIMED_REFER_REWARD_FAIL = "CLAIMED_REFER_REWARD_FAIL";  


export const ALL_DEPOSIT_REQ_BY_ALL_USERS_REQUEST = "ALL_DEPOSIT_REQ_BY_ALL_USERS_REQUEST";
export const ALL_DEPOSIT_REQ_BY_ALL_USERS_SUCCESS = "ALL_DEPOSIT_REQ_BY_ALL_USERS_SUCCESS";
export const ALL_DEPOSIT_REQ_BY_ALL_USERS_FAIL = "ALL_DEPOSIT_REQ_BY_ALL_USERS_FAIL";  


export const WALLET_BALANCE_REQUEST = "WALLET_BALANCE_REQUEST";
export const WALLET_BALANCE_SUCCESS = "WALLET_BALANCE_SUCCESS";
export const WALLET_BALANCE_FAIL = "WALLET_BALANCE_FAIL";  
 
export const GET_BANKDETAILS_REQUEST = "GET_BANKDETAILS_REQUEST";
export const GET_BANKDETAILS_SUCCESS = "GET_BANKDETAILS_SUCCESS";
export const GET_BANKDETAILST_FAIL = "GET_BANKDETAILS_FAIL";  
 
export const GET_REFER_USER_REQUEST = "GET_REFER_USER_REQUEST";
export const GET_REFER_USER_SUCCESS = "GET_REFER_USER_SUCCESS";
export const GET_REFER_USER_FAIL = "GET_REFER_USER_FAIL";  
 
export const GET_REFER_USER_DEPOSIT_DETAILS_REQUEST = "GET_REFER_USER_DEPOSIT_DETAILS_REQUEST";
export const GET_REFER_USER_DEPOSIT_DETAILS_SUCCESS = "GET_REFER_USER_DEPOSIT_DETAILS_SUCCESS";
export const GET_REFER_USER_DEPOSIT_DETAILS_FAIL = "GET_REFER_USER_DEPOSIT_DETAILS_FAIL";  
 
 
export const GET_UPIDETAILS_REQUEST = "GET_UPIDETAILS_REQUEST";
export const GET_UPIDETAILS_SUCCESS = "GET_UPIDETAILS_SUCCESS";
export const GET_UPIDETAILS_FAIL = "GET_UPIDETAILS_FAIL";  
 
export const UDPATE_UPIDETAILS_REQUEST = "UDPATE_UPIDETAILS_REQUEST";
export const UDPATE_UPIDETAILS_SUCCESS = "UDPATE_UPIDETAILS_SUCCESS";
export const UDPATE_UPIDETAILS_FAIL = "UDPATE_UPIDETAILS_FAIL";  
 
 


export const CLEAR_ERRORS = "CLEAR_ERRORS"